equivalencia_estadiamento = {
    '0': ['0', 'Tis', 'N0', 'M0'],
    'I': ['I', 'IA', 'IB', 'IC', 'M0', 'T0', 'T1', 'N1mi'],
    'II': ['II', 'IIA', 'IIB', 'IIC', 'M0', 'TO', 'N1', 'T1', 'T2', 'N0', 'T3'],
    'III': ['III', 'IIIA', 'IIIB', 'IIIb', 'IIIC', 'M0', 'N3','Tx', 'T0', 'Ta', 'Tis', 'Tis(DCIS)', 'Tis(LAMN)', 'Tis(Paget)', 'T1', 'T1mi',
          'T1a', 'T1a1', 'T1a2', 'T1b', 'T1b1', 'T1b2', 'T1b3', 'T1c', 'T1c1', 'T1c2',
          'T1c3', 'T1d', 'T2', 'T2a', 'T2a1', 'T2a2', 'T2b', 'T2c', 'T2d', 'T3', 'T3a', 'T3b', 'T3c', 'T3d', 'T3e', 'T4', 'T4a', 'T4b', 'T4c', 'T4d', 'T4e' ],
    'IV': ['IV', 'M1' 'IVA', 'IVB', 'IVC','Tx', 'T0', 'Ta', 'Tis', 'Tis(DCIS)', 'Tis(LAMN)', 'Tis(Paget)', 'T1', 'T1mi',
          'T1a', 'T1a1', 'T1a2', 'T1b', 'T1b1', 'T1b2', 'T1b3', 'T1c', 'T1c1', 'T1c2',
          'T1c3', 'T1d', 'T2', 'T2a', 'T2a1', 'T2a2', 'T2b', 'T2c', 'T2d', 'T3', 'T3a', 'T3b', 'T3c', 'T3d', 'T3e', 'T4', 'T4a', 'T4b', 'T4c', 'T4d', 'T4e',
          'Nx', 'N0', 'N0(sn)', 'N0a', 'N0a(sn)', 'N0b', 'N0b(sn)', 'N0(i+)', 'N0(mol+)', 'N1', 'N1(sn)', 'N1mi', 'N1mi(sn)', 'N1a', 'N1a(sn)', 'N1b', 'N1b(sn)', 'N1c', 'N1c(sn)', 'N2', 'N2mi', 'N2a', 'N2b', 'N2c', 'N3', 'N3a', 'N3b', 'N3c' ],
}

biomarcadores_dict = {
    'Adenocarcinoma':['HER','PD-L1'], 
    'Anus Neoplasms':[], 
    'Biliary Tract Neoplasms':[], 
    'Breast Neoplasms':['HER', 'Progesterone', 'Estrogen', 'Ki-67' ,'EGFR','ALK','BRCA1', 'BRCA2','PD-L1'], 
    'Cancer Pain':[], 
    'Carcinoma':['HER', 'Progesterone', 'Estrogen', 'MSI','BRAF','EGFR','ALK','ROS1','PD-L1'], 
    'Carcinoma, Merkel Cell':['HER', 'Progesterone', 'Estrogen', 'PD-L1'], 
    'Carcinoma, Non-Small-Cell Lung':['HER', 'Progesterone', 'Estrogen', 'BRAF','KRAS','EGFR','ALK','ROS1','PD-L1'], 
    'Carcinoma, Squamous Cell':['HER', 'Progesterone', 'Estrogen', 'PD-L1'], 
    'Cardiotoxicity':[], 
    'Cardiovascular Diseases':[], 
    'Cholangiocarcinoma':[], 
    'Colonic Neoplasms':[], 
    'Colorectal Neoplasms':['HER', 'Progesterone', 'Estrogen', 'MSI'], 
    'Endometrial Neoplasms':[], 
    'Esophageal Neoplasms':['HER', 'Progesterone', 'Estrogen', 'PD-L1'], 
    'Esophageal Squamous Cell Carcinoma':['HER', 'Progesterone', 'Estrogen', 'BRAF','EGFR','ALK','ROS1','PD-L1'], 
    'Gastrointestinal Stromal Tumors':[], 
    'Glioblastoma':['HER', 'Progesterone', 'Estrogen', 'BRAF'], 
    'Head and Neck Neoplasms':['HER', 'Progesterone', 'Estrogen', 'EGFR'], 
    'Hemangioma':[], 
    'Hematologic Neoplasms':[], 
    'Infections':[], 
    'Kidney Neoplasms':[], 
    'Leukemia':['HER', 'Progesterone', 'Estrogen', 'EGFR'], 
    'Lung Neoplasms':['HER', 'Progesterone', 'Estrogen', 'BRAF','KRAS','EGFR','ALK','ROS1','PD-L1'], 
    'Lymphoma':['HER', 'Progesterone', 'Estrogen', 'EGFR','PD-L1'], 
    'Melanoma':['HER', 'Progesterone', 'Estrogen', 'BRAF','ALK','PD-L1'], 
    'Mesothelioma':[], 
    'Mouth Neoplasms':[], 
    'Mucositis':[], 
    'Multiple Myeloma':['HER', 'Progesterone', 'Estrogen', 'EGFR','PD-L1'], 
    'Myasthenia Gravis':[], 
    'Neoplasm Metastasis':[], 
    'Neoplasms':['HER', 'Progesterone', 'Estrogen', 'Ki-67','MSI','BRAF','EGFR','ALK','ROS1','PD-L1'], 
    'Osteosarcoma':[], 
    'Papillomavirus Infections':[], 
    'Polycythemia Vera':[], 
    'Postoperative Complications':[], 
    'Preleukemia':[], 
    'Primary Myelofibrosis':[], 
    'Primary Ovarian Insufficiency':[], 
    'Prostatic Neoplasms':['HER', 'Progesterone', 'Estrogen', 'EGFR','ALK'], 
    'Rectal Neoplasms':[], 
    'Sarcoma':[], 
    'Sarcoma, Kaposi':[], 
    'Squamous Cell Carcinoma of Head and Neck':['HER', 'Progesterone', 'Estrogen', 'MSI','BRAF','EGFR','PD-L1'], 
    'Stomach Neoplasms':['HER', 'Progesterone', 'Estrogen'], 
    'Thromboembolism':[], 
    'Thyroid Diseases':[], 
    'Thyroid Neoplasms':['HER', 'Progesterone', 'Estrogen', 'BRAF','EGFR'], 
    'Thyroid Nodule':[], 
    'Urinary Bladder Neoplasms':['HER', 'Progesterone', 'Estrogen', 'PD-L1'], 
    'Uterine Cervical Neoplasms':['HER', 'Progesterone', 'Estrogen', 'ALK','PD-L1'], 
    'Ventricular Dysfunction':['HER'], 
    'Virus Diseases':[]
}


mesh_dict = {'Lung Neoplasms': ['Carcinoma, Non-Small-Cell Lung'],
             'Biliary Tract Neoplasms': [],
             'Esophageal Neoplasms': ['Esophageal Squamous Cell Carcinoma'], 
             'Lymphoma': ['Lymphoma, Non-Hodgkin', 'Lymphoma, B-Cell'], 
             'Neoplasms': [], 
             'Breast Neoplasms': [], 
             'Carcinoma': ['Carcinoma, Squamous Cell', 'Squamous Cell Carcinoma of Head and Neck'], 
             'Primary Ovarian Insufficiency': ['Menopause, Premature'], 
             'Neoplasm Metastasis': ['Sarcoma'], 
             'Leukemia': ['Leukemia, Lymphoid', 'Leukemia, Lymphocytic, Chronic, B-Cell'], 
             'Carcinoma, Squamous Cell': ['Squamous Cell Carcinoma of Head and Neck', 'Head and Neck Neoplasms'], 
             'Multiple Myeloma': ['Neoplasms, Plasma Cell'], 
             'Carcinoma, Non-Small-Cell Lung': [], 
             'Melanoma': [],
             'Uterine Cervical Neoplasms': [], 
             'Urinary Bladder Neoplasms': ['Non-Muscle Invasive Bladder Neoplasms'], 
             'Prostatic Neoplasms': ['Hypersensitivity'], 
             'Sarcoma, Kaposi': ['Sarcoma'], 
             'Adenocarcinoma': ['Stomach Neoplasms'], 
             'Head and Neck Neoplasms': [], 
             'Carcinoma, Merkel Cell': ['Carcinoma'], 
             'Preleukemia': ['Anemia', 'Myelodysplastic Syndromes', 'Syndrome'], 
             'Endometrial Neoplasms': [], 
             'Cholangiocarcinoma': [], 
             'Thromboembolism': ['Venous Thromboembolism'], 
             'Polycythemia Vera': ['Primary Myelofibrosis', 'Polycythemia', 'Thrombocytosis', 'Thrombocythemia, Essential'], 
             'Colorectal Neoplasms': [], 
             'Papillomavirus Infections': ['Uterine Cervical Neoplasms'], 
             'Mucositis': ['Xerostomia'], 
             'Sarcoma': [], 
             'Infections': ['Communicable Diseases', 'Papillomavirus Infections', 'Squamous Cell Carcinoma of Head and Neck'], 
             'Hematologic Neoplasms': ['Graft vs Host Disease'], 
             'Osteosarcoma': ['Mucositis', 'Stomatitis'], 
             'Virus Diseases': ['Neoplasms', 'Hematologic Neoplasms', 'Graft vs Host Disease'], 
             'Stomach Neoplasms': [], 
             'Glioblastoma': [], 
             'Thyroid Diseases': [], 
             'Thyroid Nodule': ['Thyroid Diseases'], 
             'Myasthenia Gravis': ['Muscle Weakness'], 
             'Epstein-Barr Virus Infections': ['Lymphoma', 'Lymphoproliferative Disorders'], 
             'Mouth Neoplasms': ['Head and Neck Neoplasms', 'Mucositis', 'Stomatitis'], 
             'Cardiovascular Diseases': ['Cardiotoxicity'], 
             'Mesothelioma': ['Mesothelioma, Malignant'], 
             'Epilepsy': [], 
             'Esophageal Squamous Cell Carcinoma': [], 
             'Anus Neoplasms': [], 
             'Cardiotoxicity': [], 
             'Colonic Neoplasms': ['Thrombosis', 'Venous Thrombosis'], 
             'Thyroid Neoplasms': ['Thyroid Diseases'], 
             'Postoperative Complications': ['Postoperative Nausea and Vomiting'], 
             'Kidney Neoplasms': ['Carcinoma, Renal Cell'], 
             'Ventricular Dysfunction': ['Ventricular Dysfunction, Left'], 
             'Primary Myelofibrosis': [], 
             'Hemangioma': ['Arteriovenous Malformations', 'Congenital Abnormalities'], 
             'Cancer Pain': [], 
             'Squamous Cell Carcinoma of Head and Neck': [], 
             'Rectal Neoplasms': [], 
             'Gastrointestinal Stromal Tumors': []}

opcoes_biomarcadores = {
    'HER': ['positivo', 'negativo', 'inconclusivo'],
    'Estrogen': ['positivo', 'negativo'],
    'Progesterone': ['positivo', 'negativo'],
    'KRAS': ['mutado', 'não-mutado'],
    'PD-L1': ['positivo', 'negativo'],
    'MSI': ['alto', 'baixo'],
    'ALK': ['mutado', 'não-mutado'],
    'BRCA1': ['mutado', 'não-mutado'],
    'BRCA2': ['mutado', 'não-mutado'],
    'BRAF': ['mutado', 'não-mutado'],
    'ROS1': ['mutado', 'não-mutado'],
    'Ki-67': [],
    'EGFR': ['mutado', 'não-mutado'],
}

bio_to_column = {
    'HER': 'Tipo_Her',
    'Estrogen': 'tipo_estrogen',
    'Progesterone': 'tipo_progesterone',
    'KRAS': 'BiomarkKRAS',
    'PD-L1': 'Tipo_PD_L1',
    'MSI': 'Tipo_MSI',
    'ALK': 'Tipo_ALK',
    'BRAF': 'Tipo_BRAF',
    'ROS1': 'Tipo_ROS1',
    'BRCA1': 'Tipo_BRCA1_BRCA2',
    'BRCA2': 'Tipo_BRCA1_BRCA2', 
    'Ki-67': 'Tipo_de_resultado_Ki67',
    'EGFR': 'Tipo_EGFR'
}
